language: python
services:
- docker
python:
- 3.6
env:
  global: RAROG_TEST_DB_PORT=4242
before_install:
- docker run -d --ulimit nofile=262144:262144 -p $RAROG_TEST_DB_PORT:9000 yandex/clickhouse-server
install:
- pip install tox codecov
script:
- tox
after_success:
- codecov
deploy:
  provider: pypi
  user: ikhlestov
  password:
    secure: VnE/LmbTOc7DlBj6Eq2EDVPcVgMW4NgvpZAZpq2rf7Y4PVhvxA5YVH6o8Vx5v2DmODpbfX+3P5uHrfyHn1U4JhBdJdMzhCegd00egO99qlO4Wyq5QhkAks4vJvJeNW+4YiKTX4NX/gpomZ0sBFWYTnRZe5aVRDbXdPcqaZxpisiQaom4FJk4EB7stCmN99DWo5eoiiFwjUOOAahpaK/YSrDD5luuucbIS1fmjLmcMQ9+FNiNKMbmICwH8K8vf/wKquNDtCVNNjYlza5hZsxP2aQAPm4OomC3vW1FaAXY3yKP8Isy5Lwipwn4luywC+t/yk9MF8rzi67/OSWNWZCEP/sDvIvXB5NSZ/jgKHsdCAIIRstyKAWgNN5uEcNn1+JL+qN2sDYIkgjTskLS0zeBPP3tk3YOKeEYbVfOg1qC8ogLeHK89LhPnuty8ZRmpHTgeKMzLPQIQlgyym4ezyiAk7em44oKssYrxj1wQvHIdLg4gzozGYk2oP5fyG5AOD7Ms+w3KzdKWLmAcEaZDHwuwwZ7xGIh1Ms8TSdM/2B9x7D2Rc67PsDp92pSJ2rAaJ3lUNDAQvGpXgv6C+smYdLVlqYhjhttcbeRSOz2LBBXy2Ys5m9hcfKEgwPdlMttAjB0cRLD1LejHeIqFjb5KNIHWRd2352tLMuJw5ALEDTFsU0=
  skip_existing: true
  on:
    all_branches: true
